[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[terminal]
shell = { program = "tmux" }

[window]
title = ""
dynamic_title = false
decorations_theme_variant = "Dark"
decorations = "none"

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 10

[keyboard]
bindings = [
  { key = "N", mods = "Control | Shift", action = "CreateNewWindow" },
  { key = "T", mods = "Control | Shift", action = "CreateNewWindow" },
  { key = "W", mods = "Control | Shift", action = "Quit" },
]
